// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUbLvFVa5wZKPjLfvnK7M9_3iZUCFtuIc',
    appId: '1:755230109966:web:093c96081753ae2cece75f',
    messagingSenderId: '755230109966',
    projectId: 'todo-app-ed468',
    authDomain: 'todo-app-ed468.firebaseapp.com',
    storageBucket: 'todo-app-ed468.appspot.com',
    measurementId: 'G-G6QXH06RZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5TqtoNEIwlQO-bKw8gM19X92-817X8WU',
    appId: '1:755230109966:android:afe546f05d142a16ece75f',
    messagingSenderId: '755230109966',
    projectId: 'todo-app-ed468',
    storageBucket: 'todo-app-ed468.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNQwWCaZsotDyAKZSSSTfjogSJvPCycio',
    appId: '1:755230109966:ios:c1251f38cf42353bece75f',
    messagingSenderId: '755230109966',
    projectId: 'todo-app-ed468',
    storageBucket: 'todo-app-ed468.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUbLvFVa5wZKPjLfvnK7M9_3iZUCFtuIc',
    appId: '1:755230109966:web:a43f885b472d2c97ece75f',
    messagingSenderId: '755230109966',
    projectId: 'todo-app-ed468',
    authDomain: 'todo-app-ed468.firebaseapp.com',
    storageBucket: 'todo-app-ed468.appspot.com',
    measurementId: 'G-EKDH4FSZYK',
  );
}
